version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: group1database
    volumes:
      - ./sql_scripts:/sql_scripts

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
