version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306' 
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: group1database
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
    volumes:
       - ./sql_scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
